namespace OldenEraTemplateEditor.Services.ContentManagement
{
    public static class ContentItemGroup
    {
        /* ContentIds of mines */
        public static readonly List<SidMapping> Mines = new List<SidMapping>() {
            ContentIds.AlchemyLab,
            ContentIds.MineCrystals,
            ContentIds.MineGemstones,
            ContentIds.MineGold,
            ContentIds.MineMercury,
            ContentIds.MineOre,
            IncludeListIds.RandomRareMines,
            IncludeListIds.RandomRareMinesBiomeRestricted,
            ContentIds.MineWood,
        }.OrderBy(x => x.Name).ToList();
        /* ContentIds of utility structures */
        public static readonly List<SidMapping> UtilityStructures = new List<SidMapping>()
        {
            ContentIds.TreeOfAbundance,
            ContentIds.BeerFountain,
            ContentIds.Chimerologist,
            ContentIds.CrystalTrail,
            ContentIds.EternalDragon,
            ContentIds.Forge,
            ContentIds.Fountain,
            ContentIds.Fountain2,
            ContentIds.InsarasEye,
            ContentIds.Market,
            ContentIds.PileOfBooks,
            ContentIds.QuixsPath,
            IncludeListIds.VisionBuildingsTier1,
            IncludeListIds.VisionBuildingsTier2,
            ContentIds.Watchtower,
            ContentIds.RemoteFoothold,
            ContentIds.SacrificialShrine,
            ContentIds.Stables,
            ContentIds.Tavern,
            ContentIds.TearOfTruth,
            ContentIds.TownGate,
            ContentIds.ManaWell,
            ContentIds.MysteriousStone,
            ContentIds.WindRose,
            ContentIds.FlatteringMirror,
        }.OrderBy(x => x.Name).ToList();
        /* ContentIds of treasures */
        public static readonly List<SidMapping> Treasures = new List<SidMapping>() { 
            ContentIds.EnchantedScrollBox,
            ContentIds.Prison,
            ContentIds.ScrollBox,
            ContentIds.Mirage,
            ContentIds.MythicScrollBox,
            IncludeListIds.PandoraBoxArmyHighTier,
            IncludeListIds.PandoraBoxArmyLowTier,
            IncludeListIds.PandoraBoxArmy,
            IncludeListIds.PandoraBoxExp,
            IncludeListIds.PandoraBoxGold,
            IncludeListIds.PandoraBoxHeroStats,
            IncludeListIds.PandoraBoxMagicSchool,
            IncludeListIds.PandoraBoxMagicTier,
            ContentIds.PandoraBox,
            ContentIds.RandomItemCommon,
            ContentIds.RandomItemEpic,
            ContentIds.RandomItemLegendary,
            ContentIds.RandomItemRare,
            IncludeListIds.MythicScrollBoxPickup,
            IncludeListIds.RandomPickupItems,
        }.OrderBy(x => x.Name).ToList();
        /* Unit recruitment buildings  */
        public static readonly List<SidMapping> UnitRecruitment = new List<SidMapping>()
        {
            ContentIds.BorealCall,
            ContentIds.TheGorge,
            ContentIds.JoustingRange,
            ContentIds.MercenaryGuild,
            ContentIds.PetrifiedMemorial,
            ContentIds.PointOfBalance,
            IncludeListIds.RandomGuardedUnitBank,
            ContentIds.RandomHire1,
            ContentIds.RandomHire2,
            ContentIds.RandomHire3,
            ContentIds.RandomHire4,
            ContentIds.RandomHire5,
            ContentIds.RandomHire6,
            ContentIds.RandomHire7,
            IncludeListIds.RandomHiresAllTier,
            IncludeListIds.RandomHiresAllTierWeighted,
            IncludeListIds.RandomHiresHighTier,
            IncludeListIds.RandomHiresLowTier,
            ContentIds.RitualPyre,
            ContentIds.UnforgottenGrave,
        }.OrderBy(x => x.Name).ToList();
        /* Resource banks */
        public static readonly List<SidMapping> ResourceBanks = new List<SidMapping>()
        {
            ContentIds.PeasantCart,
            ContentIds.AbandonedMansion,
            ContentIds.AbnormalStructure,
            ContentIds.StorageDust,
            ContentIds.AlvarsEye,
            ContentIds.OvergrownGrave,
            ContentIds.BlackTower,
            ContentIds.CircleOfLife,
            ContentIds.CrowNest,
            ContentIds.StorageCrystals,
            ContentIds.CursedOldHouse,
            ContentIds.DragonUtopia,
            IncludeListIds.EpicGuardedResourceBanks,
            ContentIds.AbandonedCorpse,
            ContentIds.StorageGemstones,
            ContentIds.GingerbreadHouse,
            ContentIds.GoblinCache,
            ContentIds.StorageGold,
            IncludeListIds.GuardedBanksTier1,
            IncludeListIds.GuardedBanksTier2,
            IncludeListIds.GuardedBanksTier3,
            IncludeListIds.GuardedUnitBanksBiomeRestricted,
            IncludeListIds.GuardedUnitBanksNoBiome,
            ContentIds.IridescentAbbey,
            ContentIds.LegionsMemorial,
            ContentIds.Gardener,
            ContentIds.MereasShrine,
            ContentIds.StorageMercury,
            ContentIds.StorageOre,
            ContentIds.UnstableRuins,
            ContentIds.PrismaticLair,
            ContentIds.RaidersCamp,
            IncludeListIds.BasicStorageBanks,
            ContentIds.ResearchLaboratory,
            IncludeListIds.ResourceBanksTier1,
            IncludeListIds.ResourceBanksTier2,
            ContentIds.MontyHall,
            ContentIds.HerosCrypt,
            ContentIds.ShadyDen,
            ContentIds.TroglodyteThrone,
            ContentIds.TwilightBloom,
            ContentIds.UncannyRite,
            IncludeListIds.UtopiaBuildings,
            ContentIds.Village,
            ContentIds.Windmill,
            ContentIds.StorageWood,
        }.OrderBy(x => x.Name).ToList();
        /* Hero improvement structures */
        public static readonly List<SidMapping> HeroImprovementStructures = new List<SidMapping>()
        {
            ContentIds.MysticalTower,
            ContentIds.MagicAmplifier3,
            ContentIds.AltarOfMagic3,
            ContentIds.CelestialSphere,
            ContentIds.MagicAmplifier2,
            ContentIds.AltarOfMagic2,
            ContentIds.HuntsmansCamp,
            ContentIds.OrbObservatory,
            ContentIds.FickleShrine,
            ContentIds.InfernalCirque,
            ContentIds.KnowledgeGarden,
            ContentIds.LearningStone,
            ContentIds.Maze,
            ContentIds.LostLibrary,
            ContentIds.MagicWheel,
            ContentIds.CollegeOfWonder,
            ContentIds.MagicAmplifier1,
            ContentIds.AltarOfMagic1,
            ContentIds.Fort,
            ContentIds.Arena,
            ContentIds.MagicAmplifier4,
            ContentIds.AltarOfMagic4,
            IncludeListIds.HeroBuffTier1,
            IncludeListIds.HeroExpTier2,
            IncludeListIds.HeroStatsAndSkillsTier1,
            IncludeListIds.HeroStatsAndSkillsTier2,
            IncludeListIds.HeroStatsAndSkillsTier3,
            IncludeListIds.MagicBuildingsTier1,
            IncludeListIds.MagicBuildingsTier2,
            ContentIds.TrialScales,
            ContentIds.StingingSword,
            ContentIds.ArmoryAutomaton,
            ContentIds.Circus,
            ContentIds.TreeOfKnowledge,
            IncludeListIds.HeroImprovementUncommon,
            ContentIds.University,
            ContentIds.WiseOwl,
        }.OrderBy(x => x.Name).ToList();

    }

}